@startuml
!define KO_KOTLIN
!define KO_ICON
skinparam class {
    BackgroundColor White
    ArrowColor SeaGreen
    BorderColor Black
}

Department <|-- AcademicDepartment
Department <|-- NonAcademicDepartment

Student <|-- UndergraduateStudent
Student <|-- PostGraduateStudent
Student <|-- PhdStudent
Student <|-- PostDocStudent

Course <|-- UndergraduateCourse
Course <|-- PostGraduateCourse
Course <|-- PhdCourse
Course <|-- PostDocCourse

Staff <|-- AcademicStaff
Staff <|-- NonAcademicStaff
Staff <|-- VisitingStaff

SalaryCalculator <|.. AcademicSalaryCalculator
SalaryCalculator <|.. VisitingSalaryCalculator

EngagementStrategy <|.. LectureEngagement
EngagementStrategy <|.. WorkshopEngagement

DetailedAddress <|.. Address

CourseTypeProvider <|.. UndergraduateStudent
CourseTypeProvider <|.. PostGraduateStudent
CourseTypeProvider <|.. PhdStudent

TenureProvider <|.. UndergraduateCourse
TenureProvider <|.. PostGraduateCourse

MaterialPreperator <|.. LectureEngagement

SalaryReceivingStaff <|.. AcademicStaff
SalaryReceivingStaff <|.. NonAcademicStaff

IStudentManager <|.. StudentManager
IStaffManager <|.. StaffManager
StaffManager <|.. EngagementManager
@enduml